Trying to make process more efficient.
Most of this commit is an attempt to do the following:
- move all configuration details into ./config
- make package selection slightly more dynamic
- rename some scripts to be more generic
- change some variable names to be more descriptive

diff --git a/bin/partition b/bin/partition
--- a/bin/partition
+++ b/bin/partition
@@ -2,13 +2,20 @@
 
 set -eu
 
-if [[ -v INSTALL_EFI_DIR ]]; then
+case $INSTALL_BOOT_TYPE in
+uefi)
     boot_size=512
     boot_type=esp
-else
+    ;;
+bios)
     boot_size=2
     boot_type=bios_grub
-fi
+    ;;
+*)
+    echo "${0##*/}: Invalid boot type: $INSTALL_BOOT_TYPE" >&2
+    exit 1
+    ;;
+esac
 
 parted -s "$INSTALL_DEVICE" \
     mklabel gpt unit MiB \
