Tinkering

diff --git a/scripts/prepare b/scripts/prepare
--- a/scripts/prepare
+++ b/scripts/prepare
@@ -37,27 +37,27 @@ fi
 
 export BOOTSTRAP_LVM_VG_NAME=${BOOTSTRAP_LVM_VG_NAME:-sys}
 
-export BOOTSTRAP_LVM_LV_SWAP_NAME=${BOOTSTRAP_LVM_LV_SWAP_NAME:-swap}
-
-if [[ ! -v BOOTSTRAP_LVM_LV_SWAP_SIZE ]]; then
-    if [[ -v BOOTSTRAP_MEMORY_SIZE ]]; then
-        BOOTSTRAP_LVM_LV_SWAP_SIZE=$BOOTSTRAP_MEMORY_SIZE
-    elif memory_size=$(memory-size); then
-        BOOTSTRAP_LVM_LV_SWAP_SIZE=$memory_size
-    else
-        printf "unable to get information about physical memory\n" >&2
-        return 1
+if [[ -v BOOTSTRAP_USE_SWAP ]]; then
+    export BOOTSTRAP_LVM_LV_SWAP_NAME=${BOOTSTRAP_LVM_LV_SWAP_NAME:-swap}
+    export BOOTSTRAP_SWAP_DEVICE=/dev/mapper/$BOOTSTRAP_LVM_VG_NAME-$BOOTSTRAP_LVM_LV_SWAP_NAME
+    export BOOTSTRAP_FS_SWAP_LABEL=${BOOTSTRAP_FS_SWAP_LABEL:-swap}
+    if [[ ! -v BOOTSTRAP_LVM_LV_SWAP_SIZE ]]; then
+        if [[ -v BOOTSTRAP_MEMORY_SIZE ]]; then
+            BOOTSTRAP_LVM_LV_SWAP_SIZE=$BOOTSTRAP_MEMORY_SIZE
+        elif memory_size=$(memory-size); then
+            BOOTSTRAP_LVM_LV_SWAP_SIZE=$memory_size
+        else
+            printf "unable to get information about physical memory\n" >&2
+            return 1
+        fi
+        export BOOTSTRAP_LVM_LV_SWAP_SIZE
     fi
-    export BOOTSTRAP_LVM_LV_SWAP_SIZE
 fi
 
 export BOOTSTRAP_LVM_LV_ROOT_NAME=${BOOTSTRAP_LVM_LV_ROOT_NAME:-root}
 export BOOTSTRAP_LVM_LV_ROOT_EXTENTS=${BOOTSTRAP_LVM_LV_ROOT_EXTENTS:-+100%FREE}
-
 export BOOTSTRAP_ROOT_DEVICE=/dev/mapper/$BOOTSTRAP_LVM_VG_NAME-$BOOTSTRAP_LVM_LV_ROOT_NAME
-export BOOTSTRAP_SWAP_DEVICE=/dev/mapper/$BOOTSTRAP_LVM_VG_NAME-$BOOTSTRAP_LVM_LV_SWAP_NAME
 
-export BOOTSTRAP_FS_SWAP_LABEL=${BOOTSTRAP_FS_SWAP_LABEL:-swap}
 export BOOTSTRAP_FS_ROOT_LABEL=${BOOTSTRAP_FS_ROOT_LABEL:-root}
 export BOOTSTRAP_FS_ROOT_OPTIONS=${BOOTSTRAP_FS_ROOT_OPTIONS:-autodefrag,compress=zstd}
 
@@ -140,7 +140,7 @@ if [[ -v BOOTSTRAP_ADMIN_SHELL ]]; then
 fi
 export BOOTSTRAP_ADMIN_SHELL_PACKAGE
 
-kernel=linux${BOOTSTRAP_KERNEL:+-$BOOTSTRAP_KERNEL}
+kernel=linux${BOOTSTRAP_KERNEL_ALT:+-$BOOTSTRAP_KERNEL_ALT}
 if ! grep -qxF "$kernel" "$BOOTSTRAP_CONFIG"/packages/kernel; then
     printf "%s: invalid kernel: %s\n" "$0" "$kernel" >&2
     return 2
