Tinkering

diff --git a/scripts/prepare b/scripts/prepare
--- a/scripts/prepare
+++ b/scripts/prepare
@@ -1,21 +1,23 @@
 #!/usr/bin/env bash
 
+export PATH=$PWD/bin:$PATH
+
 export INSTALL_CONFIG=${INSTALL_CONFIG:-$PWD/config}
 
-if [[ -f $INSTALL_CONFIG/env ]]; then
-    source "$INSTALL_CONFIG"/env || return 1
+env_file=$INSTALL_CONFIG/env
+if [[ -f $env_file ]] && ! . "$env_file"; then
+    printf "unable to source file: %q\n" "$env_file" >&2
+    return 1
 fi
-
-export PATH=$PWD/bin:$PATH
 
 export INSTALL_MOUNT=${INSTALL_MOUNT:-/mnt/install}
 
 export INSTALL_BOOT_DEVICE=${INSTALL_DEVICE}1
 export INSTALL_SYS_DEVICE=${INSTALL_DEVICE}2
 
-export INSTALL_DEVICE_IS_ENCRYPTED=${INSTALL_DEVICE_IS_ENCRYPTED:-0}
+export INSTALL_DEVICE_IS_LUKS=${INSTALL_DEVICE_IS_LUKS:-0}
 
-if ((INSTALL_DEVICE_IS_ENCRYPTED)); then
+if ((INSTALL_DEVICE_IS_LUKS)); then
     export INSTALL_LUKS_DEVICE=$INSTALL_SYS_DEVICE
     export INSTALL_LUKS_MAPPER_NAME=${INSTALL_LUKS_MAPPER_NAME:-sys}
     export INSTALL_LUKS_MAPPER=/dev/mapper/$INSTALL_LUKS_MAPPER_NAME
@@ -74,23 +76,24 @@ if [[ ! -v INSTALL_BOOT_FIRMWARE ]]; then
 fi
 
 export INSTALL_BOOT_PART_NAME=${INSTALL_BOOT_PART_NAME:-boot}
-export INSTALL_BOOT_PART_START=${INSTALL_BOOT_PART_START:-0%}
+export INSTALL_BOOT_PART_START=${INSTALL_BOOT_PART_START:-}
 
 case $INSTALL_BOOT_FIRMWARE in
 uefi)
-    export INSTALL_BOOT_PART_FLAG=esp
-    export INSTALL_BOOT_PART_END=${INSTALL_BOOT_PART_END:-512MiB}
-    export INSTALL_UEFI_MOUNT=${INSTALL_UEFI_MOUNT:-/boot/efi}
+    export INSTALL_BOOT_PART_TYPE=C12A7328-F81F-11D2-BA4B-00A0C93EC93B
+    export INSTALL_BOOT_PART_SIZE=${INSTALL_BOOT_PART_SIZE:-100M}
+    export INSTALL_UEFI_MOUNT=${INSTALL_UEFI_MOUNT:-/efi}
     ;;
 bios)
-    export INSTALL_BOOT_PART_FLAG=bios_grub
-    export INSTALL_BOOT_PART_END=${INSTALL_BOOT_PART_END:-2MiB}
+    export INSTALL_BOOT_PART_TYPE=21686148-6449-6E6F-744E-656564454649
+    export INSTALL_BOOT_PART_SIZE=${INSTALL_BOOT_PART_SIZE:-1M}
     ;;
 esac
 
 export INSTALL_SYS_PART_NAME=${INSTALL_SYS_PART_NAME:-sys}
-export INSTALL_SYS_PART_START=${INSTALL_SYS_PART_START:-$INSTALL_BOOT_PART_END}
-export INSTALL_SYS_PART_END=${INSTALL_SYS_PART_END:-100%}
+export INSTALL_SYS_PART_TYPE=${INSTALL_SYS_PART_TYPE:-0FC63DAF-8483-4772-8E79-3D69D8477DE4}
+export INSTALL_SYS_PART_START=${INSTALL_SYS_PART_START:-}
+export INSTALL_SYS_PART_SIZE=${INSTALL_SYS_PART_SIZE:-+}
 
 if [[ ! -v INSTALL_DEVICE_IS_SSD ]]; then
     if is-device-ssd "$INSTALL_DEVICE"; then
@@ -111,16 +114,12 @@ if [[ ! -v INSTALL_NET_HAS_WIRELESS ]]; then
 fi
 
 export INSTALL_HOSTNAME=${INSTALL_HOSTNAME:-arch}
-
 export INSTALL_LANG=${INSTALL_LANG:-en_US.UTF-8}
-export LANG=$INSTALL_LANG
-
 export INSTALL_KEYMAP=${INSTALL_KEYMAP:-us}
-export KEYMAP=$INSTALL_KEYMAP
 
 if [[ ! -v INSTALL_TIMEZONE ]]; then
     if ! INSTALL_TIMEZONE=$(get-timezone); then
-        printf "unable to get timezone\n" >&2
+        printf "unable to get time zone\n" >&2
         return 1
     fi
     export INSTALL_TIMEZONE
@@ -128,11 +127,12 @@ fi
 
 export INSTALL_REFLECTOR_COUNTRY=${INSTALL_REFLECTOR_COUNTRY:-US}
 
-export INSTALL_SUDOER_USERNAME=${INSTALL_SUDOER_USERNAME:-admin}
+export INSTALL_ROOT_PASSWORD=${INSTALL_ROOT_PASSWORD:-hunter2}
 export INSTALL_SUDOER_PASSWORD=${INSTALL_SUDOER_PASSWORD:-hunter2}
 export INSTALL_SUDOER_GROUP=${INSTALL_SUDOER_GROUP:-wheel}
 export INSTALL_SUDOER_GROUP_NOPASSWD=${INSTALL_SUDOER_GROUP_NOPASSWD:-0}
 
+export INSTALL_LOGLEVEL=${INSTALL_LOGLEVEL:-3}
 export INSTALL_CONSOLEBLANK=${INSTALL_CONSOLEBLANK:-0}
 
 # Show the current environment as a sanity check.
